loading dataset

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv('/content/drive/MyDrive/ML_Projects/Customer_Default_Prediction/data/eda_completed.csv')

Check EDUCATION

In [5]:
df['EDUCATION'].value_counts().sort_index()# lets consider 1,2,3,4 as school,highschool , university and others respectively

EDUCATION
0       14
1    10585
2    14030
3     4917
4      123
5      280
6       51
Name: count, dtype: int64

In [6]:
df['EDUCATION'] = df['EDUCATION'].replace([0,5,6], 4)

Check MARRIAGE

In [7]:
df['MARRIAGE'].value_counts().sort_index()#1 = Married, 2 = Single ,3 = Others

MARRIAGE
0       54
1    13659
2    15964
3      323
Name: count, dtype: int64

In [8]:
df['MARRIAGE'] = df['MARRIAGE'].replace(0,3)

Check for Duplicates

In [9]:
df.duplicated().sum()

np.int64(0)

total bill and total payment amount

In [10]:
df['TOTAL_BILL'] = (
    df['BILL_AMT1']
    + df['BILL_AMT2']
    + df['BILL_AMT3']
    + df['BILL_AMT4']
    + df['BILL_AMT5']
    + df['BILL_AMT6']
)

In [11]:
df['TOTAL_PAYMENT'] = (
    df['PAY_AMT1']
    + df['PAY_AMT2']
    + df['PAY_AMT3']
    + df['PAY_AMT4']
    + df['PAY_AMT5']
    + df['PAY_AMT6']
)

In [12]:
df['PAYMENT_RATIO'] = (
    df['TOTAL_PAYMENT']
    /
    (df['TOTAL_BILL'] + 1)
)

feature and target

In [13]:
X = df.drop('default.payment.next.month', axis=1)

y = df['default.payment.next.month']

train-test-split

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)#stratify to maintain class distribution for imbalanced dataset

In [16]:
import joblib

joblib.dump(scaler,
'/content/drive/MyDrive/ML_Projects/Customer_Default_Prediction/data/scaler.pkl')

['/content/drive/MyDrive/ML_Projects/Customer_Default_Prediction/data/scaler.pkl']

In [17]:
X_train.to_csv(
'/content/drive/MyDrive/ML_Projects/Customer_Default_Prediction/X_train.csv',
index=False)

X_test.to_csv(
'/content/drive/MyDrive/ML_Projects/Customer_Default_Prediction/X_test.csv',
index=False)

In [18]:
y_train.to_csv(
'/content/drive/MyDrive/ML_Projects/Customer_Default_Prediction/y_train.csv',
index=False)

y_test.to_csv(
'/content/drive/MyDrive/ML_Projects/Customer_Default_Prediction/y_test.csv',
index=False)

In [19]:
df.shape

(30000, 28)

In [20]:
X_train.shape

(24000, 27)